# Generated by Django 4.0.5 on 2022-06-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Prince dubey', max_length=100),
        ),
    ]
